Repository organicmaps/organicmaps, pull requests merged in 2022-11, with the labels that each got.

#3903 [tools] Convert more than one kmb to kml with one call
  kml/kmb_to_kml/kmb_to_kml.cpp
Labels: Bookmarks

#3980 Update sound.txt PT and PT-BR
  data/strings/sound.txt
Labels: Translations, TTS

#3912 [android] handle place page direction arrow more reliably
  android/res/layout/place_page_preview.xml
  android/src/app/organicmaps/widget/placepage/PlacePageView.java
  android/src/app/organicmaps/widget/placepage/RichPlacePageController.java
Labels: Android
