Repository organicmaps/organicmaps, pull requests merged in 2023-03, with the labels that each got.

#4575 [android] Improve theming in alertDialog on most recent devices
  android/res/values/themes-attrs.xml
  android/res/values/themes-base.xml
  android/res/values/themes.xml
Labels: Bug, Android, UX

#4784 [android] Improve style on button
  android/res/layout/fragment_map_placeholder.xml
Labels: AndroidAuto

#4830 [Desktop] Make version number selectable/copyable
  qt/about.cpp
Labels: Linux Desktop
