Repository organicmaps/organicmaps, pull requests merged in 2024-04, with the labels that each got.

#7805 [ios] Fix radiOn/Off buttons icons
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/Contents.json
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff.svg
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff@2x.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff@3x.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/Contents.json
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn.svg
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn@2x.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn@3x.png
Labels: iOS, UI

#7819 [ios] Fix the circular downloading progress bar layout on the PP screen
  iphone/Maps/Classes/CustomViews/CircularProgress/MWMCircularProgressView.m
Labels: iOS, UI

#7846 [ios] Add PrivacyInfo with missing API declarations
  iphone/Maps/Maps.xcodeproj/project.pbxproj
  iphone/Maps/PrivacyInfo.xcprivacy
Labels: iOS

#7853 [editor] Fixed bug overwriting existing features
  editor/changeset_wrapper.cpp
  editor/changeset_wrapper.hpp
  editor/osm_editor.cpp
Labels: Editor

#7919 [xcode] Disable the tests parallelizing
  iphone/Maps/Maps.xcodeproj/xcshareddata/xcschemes/OMaps.xcscheme
Labels: iOS

#7937 [ios] fix: user interface auto theme changing issue
  iphone/Maps/Classes/Components/MWMNavigationController.m
Labels: iOS

#7933 [ios] [bookmarks] Remove observer pattern during the category files exporting
  iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
  iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
  iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksObserver.h
  iphone/Maps/Bookmarks/BookmarksList/BookmarksListInteractor.swift
  iphone/Maps/Bookmarks/BookmarksList/BookmarksListInterfaces.swift
  iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift
  iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
  iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
Labels: iOS, Bookmarks and Tracks

#7699 [base] Code cleanup
  base/array_adapters.hpp
  base/base.cpp
  base/bits.hpp
  base/buffer_vector.hpp
  base/cache.hpp
  base/cancellable.cpp
  base/checked_cast.hpp
  base/control_flow.hpp
  base/deferred_task.cpp
  base/deferred_task.hpp
  base/dfa_helpers.hpp
  base/file_name_utils.cpp
  base/file_name_utils.hpp
  base/geo_object_id.cpp
  base/geo_object_id.hpp
  base/gmtime.cpp
  base/gmtime.hpp
  base/levenshtein_dfa.cpp
  base/levenshtein_dfa.hpp
  base/limited_priority_queue.hpp
  base/logging.hpp
  base/lower_case.cpp
  base/macros.hpp
  base/math.hpp
  base/matrix.hpp
  base/mem_trie.hpp
  base/newtype.hpp
  base/non_intersecting_intervals.hpp
  base/normalize_unicode.cpp
  base/random.cpp
  base/ref_counted.hpp
  base/rolling_hash.hpp
  base/scope_guard.hpp
  base/set_operations.hpp
  base/shared_buffer_manager.cpp
  base/small_set.hpp
  base/stats.hpp
  base/std_serialization.hpp
  base/stl_helpers.hpp
  base/string_utils.cpp
  base/strings_bundle.cpp
  base/sunrise_sunset.cpp
  base/thread_pool.cpp
  base/thread_pool_computational.hpp
  base/thread_pool_delayed.hpp
  base/thread_safe_queue.hpp
  base/threaded_container.cpp
  base/threaded_list.hpp
  base/timegm.cpp
  base/timegm.hpp
  base/timer.hpp
  base/waiter.hpp
Labels: Core

#7942 Better search for horse riding and skateboard.
  data/categories.txt
Labels: Translations

#7964 [android] Fix PT router overriding previous mode if subway layer active
  android/app/src/main/java/app/organicmaps/routing/RoutingController.java
Labels: Android, Route Planning

#7959 [drape] Removed fixed text size in favor of always using SDF fonts
  drape/drape_global.hpp
  drape/drape_tests/font_texture_tests.cpp
  drape/drape_tests/glyph_mng_tests.cpp
  drape/font_constants.hpp
  drape/font_texture.cpp
  drape/font_texture.hpp
  drape/glyph.hpp
  drape/glyph_manager.cpp
  drape/glyph_manager.hpp
  drape/texture_manager.cpp
  drape/texture_manager.hpp
  drape_frontend/apply_feature_functors.cpp
  drape_frontend/gui/gui_text.cpp
  drape_frontend/path_text_handle.cpp
  drape_frontend/path_text_handle.hpp
  drape_frontend/path_text_shape.cpp
  drape_frontend/text_handle.cpp
  drape_frontend/text_handle.hpp
  drape_frontend/text_layout.cpp
  drape_frontend/text_layout.hpp
  drape_frontend/text_shape.cpp
  drape_frontend/transit_scheme_builder.cpp
  drape_frontend/user_mark_shapes.cpp
  drape_frontend/visual_params.cpp
  drape_frontend/visual_params.hpp
  shaders/CMakeLists.txt
  shaders/GL/shader_index.txt
  shaders/GL/text_fixed.fsh.glsl
  shaders/Metal/map.metal
  shaders/metal_program_pool.mm
  shaders/program_params.hpp
  shaders/programs.hpp
  xcode/shaders/shaders.xcodeproj/project.pbxproj
Labels: Drape

#7973 [ios] Add a loading overlay screen with an activity indicator for the bookmarks sharing
  iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
  iphone/Maps/Categories/UIApplication+LoadingOverlay.swift
  iphone/Maps/Classes/LoadingOverlay/LoadingOverlayViewController.swift
  iphone/Maps/Maps.xcodeproj/project.pbxproj
Labels: iOS, UX, UI

#8005 [qt] Move shaders to resources
  qt/qt_common/map_widget.cpp
  qt/qt_common/res/resources_common.qrc
  qt/qt_common/res/shaders/gl_150.fsh.glsl
  qt/qt_common/res/shaders/gl_150.vsh.glsl
  qt/qt_common/res/shaders/gles_200.fsh.glsl
  qt/qt_common/res/shaders/gles_200.vsh.glsl
  qt/qt_common/res/shaders/gles_300.fsh.glsl
  qt/qt_common/res/shaders/gles_300.vsh.glsl
Labels: Desktop
