Repository organicmaps/organicmaps, pull requests merged in 2024-11, with the labels that each got.

#9588 [ios] Refactor iCloud Synchronization
  iphone/Maps/Classes/MapsAppDelegate.mm
  iphone/Maps/Core/iCloud/CloudDirectoryMonitor.swift
  iphone/Maps/Core/iCloud/LocalDirectoryMonitor.swift
  iphone/Maps/Core/iCloud/MetadataItem.swift
  iphone/Maps/Core/iCloud/SynchronizaionManager.swift
  iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
  iphone/Maps/Core/iCloud/SynchronizationStateManager.swift
  iphone/Maps/Core/iCloud/SynchronizationStateResolver.swift
  iphone/Maps/Maps.xcodeproj/project.pbxproj
  iphone/Maps/Tests/Core/iCloudTests/DefaultLocalDirectoryMonitorTests/DefaultLocalDirectoryMonitorTests.swift
  iphone/Maps/Tests/Core/iCloudTests/DefaultLocalDirectoryMonitorTests/LocalDirectoryMonitorDelegateMock.swift
  iphone/Maps/Tests/Core/iCloudTests/MetadataItemStubs.swift
  iphone/Maps/Tests/Core/iCloudTests/SynchronizationStateManagerTests.swift
  iphone/Maps/Tests/Core/iCloudTests/iCloudDirectoryMonitorTests/UbiquitousDirectoryMonitorDelegateMock.swift
  iphone/Maps/Tests/Core/iCloudTests/iCloudDirectoryMonitorTests/iCloudDirectoryMonitorTests.swift
  iphone/Maps/UI/Settings/Cells/SettingsTableViewiCloudSwitchCell.swift
  iphone/Maps/UI/Settings/MWMSettingsViewController.mm
Labels: iOS

#9637 [ios] improve icloud sync logging
  iphone/Maps/Core/iCloud/CloudDirectoryMonitor.swift
  iphone/Maps/Core/iCloud/LocalDirectoryMonitor.swift
  iphone/Maps/Core/iCloud/MetadataItem.swift
  iphone/Maps/Core/iCloud/SynchronizaionManager.swift
  iphone/Maps/Core/iCloud/SynchronizationStateResolver.swift
Labels: iOS

#9665 [drape] Removed dummy fields in StaticTexture.
  drape/static_texture.cpp
  drape/static_texture.hpp
  drape/texture_manager.cpp
  drape/texture_manager.hpp
  drape_frontend/arrow3d.cpp
  drape_frontend/backend_renderer.cpp
  drape_frontend/drape_engine_params.hpp
Labels: Drape

#9653 [ios] Implement macOS trackpad and mouse events (scroll, rotate, zoom) support
  iphone/Maps/Classes/MapViewController.mm
Labels: iOS, UX

#9730 [xcode] Revert swift version setting for CoreApi
  iphone/CoreApi/CoreApi.xcodeproj/project.pbxproj
Labels: iOS

#9695 [core] Implement products configuration
  defines.hpp
  iphone/Maps/Core/Settings/MWMSettings.mm
  map/framework.cpp
  map/framework.hpp
  platform/CMakeLists.txt
  platform/platform_tests/CMakeLists.txt
  platform/platform_tests/meta_config_tests.cpp
  platform/platform_tests/products_tests.cpp
  platform/products.cpp
  platform/products.hpp
  platform/servers_list.cpp
  platform/servers_list.hpp
  platform/settings.cpp
  platform/settings.hpp
  storage/map_files_downloader.cpp
  xcode/platform/platform.xcodeproj/project.pbxproj
Labels: Core

#9755 [ios] fix the bookmark description jumping bug during editing
  iphone/Maps/UI/EditBookmark/EditBookmarkViewController.swift
Labels: iOS, UI

#9772 [ios] Add the context menu to the coordinates accessory button
  iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
Labels: iOS, UI
