Repository organicmaps/organicmaps, pull requests merged in 2024-02, with the labels that each got.

#7314 [ios] Reduce the navigation screen top bar height
  iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm
  iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.xib
Labels: iOS, Navigation, UI

#7310 [generator][routing] Ignore "highway=construction".
  generator/feature_segments_checker/feature_segments_checker.cpp
  generator/routing_index_generator.cpp
  routing/features_road_graph.cpp
  routing/features_road_graph.hpp
  routing/geometry.cpp
  routing/routing_benchmarks/helpers.hpp
  routing_common/bicycle_model.cpp
  routing_common/bicycle_model.hpp
  routing_common/car_model.cpp
  routing_common/car_model.hpp
  routing_common/pedestrian_model.cpp
  routing_common/pedestrian_model.hpp
  routing_common/routing_common_tests/bicycle_model_test.cpp
  routing_common/routing_common_tests/vehicle_model_test.cpp
  routing_common/vehicle_model.cpp
  routing_common/vehicle_model.hpp
  track_analyzing/track_analyzer/cmd_table.cpp
  track_analyzing/track_matcher.cpp
  traffic/traffic_info.cpp
Labels: Routing

#7331 [ios] Fix the route estimates colors when the app appearance was changed
  iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.h
  iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
  iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
  iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/BaseRoutePreviewStatus.swift
  iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/TransportRoutePreviewStatus.swift
Labels: iOS, UI

#7395 [ios] Match the iOS primary OM color with the Android
  iphone/Maps/Core/Theme/Colors.swift
Labels: iOS, UI

#7383 [ios] Fix crash when user taps the Menu button during the TabBar hiding animation
  iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarInteractor.swift
Labels: Bug, iOS

#7406 [ios] Improve the search screen closing animation
  iphone/Maps/UI/Search/MWMSearchManager.mm
Labels: iOS, UI

#7425 [strings] Update PT strings opening hours editor
  data/strings/strings.txt
Labels: Translations

#7443 [ios] Extend bottom tab buttons tappable area by 15pt
  iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarButton.swift
  iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarView.swift
  iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.xib
Labels: iOS, UI

#7386 [ios] fix search bars for iOS12
  iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift
  iphone/Maps/UI/Search/SearchBar.swift
Labels: iOS, UI
