Repository organicmaps/organicmaps, pull requests merged in 2024-05, with the labels that each got.

#8060 [ios] Fix the AdditionalNameTableViewCell tappable area
  iphone/Maps/UI/Editor/Cells/MWMEditorAdditionalNameTableViewCell.m
  iphone/Maps/UI/Editor/Cells/MWMEditorAdditionalNameTableViewCell.xib
Labels: iOS, UX, UI

#8032 [ios] Fix the bug when the same language can be added multiple times to the additional languages list
  iphone/Maps/UI/Editor/MWMEditorViewController.mm
Labels: iOS, UI

#8124 [data] Remove drules_proto-bw
  data/drules_proto-bw.bin
  tools/python/data/styles/setup.py
  xcode/indexer/indexer.xcodeproj/project.pbxproj
  xcode/routing/routing.xcodeproj/project.pbxproj
  xcode/storage/storage.xcodeproj/project.pbxproj
Labels: Refactoring

#8100 [Bookmarks] Add `areAllCategoriesEmpty` method to the bookmarks manager
  iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarkGroup.m
  iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
  iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
  map/bookmark_manager.cpp
  map/bookmark_manager.hpp
Labels: Bookmarks and Tracks

#8126 Revert "[editor] Fixed bug overwriting existing features"
  editor/changeset_wrapper.cpp
  editor/changeset_wrapper.hpp
  editor/osm_editor.cpp
Labels: Editor

#8131 [drape] Fixed MutableLabelHandle mutation buffer's size.
  drape_frontend/gui/gui_text.cpp
  drape_frontend/gui/gui_text.hpp
Labels: Drape

#7652 [editor] Fix parsing of 'off' opening hours
  editor/editor_tests/ui2oh_test.cpp
  editor/ui2oh.cpp
Labels: Opening Hours

#8234 [bookmarks] Reuse the MarkGroupId during the category reloading
  map/bookmark_manager.cpp
  map/bookmark_manager.hpp
  map/map_tests/bookmarks_test.cpp
Labels: Bookmarks and Tracks, Core

#8190 [ios] Hide the `Export all bookmarks and tracks` button when there are no bookmarks
  iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
Labels: iOS, UI

#8273 [ios] fix compile error in the MWMTextToSpeechTest
  iphone/Maps/Tests/Core/TextToSpeech/MWMTextToSpeechTests.mm
Labels: Build

#8250 [ios] Fix: do not hide the side buttons during the new place adding
  iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
Labels: iOS, UI

#8308 Fix coverage check
  .github/workflows/coverage-check.yaml
Labels: Coverage

#8295 [base] Renamed XXXThreadPool for better understanding. Removed tautology namespaces.
  base/base_tests/thread_pool_computational_tests.cpp
  base/base_tests/thread_pool_delayed_tests.cpp
  base/base_tests/thread_pool_tests.cpp
  base/base_tests/thread_safe_queue_tests.cpp
  base/thread_pool.cpp
  base/thread_pool.hpp
  base/thread_pool_computational.hpp
  base/thread_pool_delayed.cpp
  base/thread_pool_delayed.hpp
  base/threaded_container.hpp
  base/threaded_list.hpp
  drape/drape_routine.hpp
  drape_frontend/drape_notifier.cpp
  drape_frontend/drape_notifier.hpp
  drape_frontend/read_manager.cpp
  drape_frontend/read_manager.hpp
  generator/affiliation.cpp
  generator/coastlines_generator.cpp
  generator/final_processor_utils.cpp
  generator/final_processor_utils.hpp
  generator/translators_pool.cpp
  generator/translators_pool.hpp
  generator/wiki_url_dumper.cpp
  map/mwm_tests/multithread_mwm_test.cpp
  map/transit/transit_reader.cpp
  map/transit/transit_reader.hpp
  platform/platform.cpp
  platform/platform.hpp
  platform/platform_tests_support/async_gui_thread.hpp
  poly_borders/borders_data.cpp
  routing/routes_builder/routes_builder.hpp
  shaders/shaders_tests/gl_shaders_mobile_compile_test.cpp
  storage/pinger.cpp
  topography_generator/generator.cpp
Labels: Generator

#8304 [search] Pastry/Cake categories.
  data/categories.txt
Labels: Search
