Repository organicmaps/organicmaps, pull requests merged in 2024-03, with the labels that each got.

#7508 [ios] New icons for the Bookmarks screen
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/Contents.json
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff.svg
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff@2x.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOff.imageset/radioBtnOff@3x.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/Contents.json
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn.svg
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn@2x.png
  iphone/Maps/Images.xcassets/DownloadMapRequest/radioBtnOn.imageset/radioBtnOn@3x.png
  iphone/Maps/Images.xcassets/Sharing/ic24PxShare.imageset/Contents.json
  iphone/Maps/Images.xcassets/Sharing/ic24PxShare.imageset/ic24PxShare.pdf
  iphone/Maps/Images.xcassets/Sharing/ic24PxShare.imageset/ic_share.svg
  iphone/Maps/Images.xcassets/ic24PxAddCopy.imageset/Contents.json
  iphone/Maps/Images.xcassets/ic24PxAddCopy.imageset/ic24PxAddCopy.pdf
  iphone/Maps/Images.xcassets/ic24PxAddCopy.imageset/ic_addCopy.svg
Labels: iOS, UI

#7519 [ios] Fix srgb color crash
  iphone/Maps/UI/ColorPicker/ColorPicker.swift
  iphone/Maps/UI/EditBookmark/EditTrackViewController.swift
Labels: iOS

#7549 [android] Upgrade NDK to r26c
  android/app/build.gradle
  docs/INSTALL.md
Labels: Android

#7570 [ios] Fix opening hours icons
  iphone/Maps/Bookmarks/BookmarksList/Cells/SubgroupCell.xib
  iphone/Maps/Bookmarks/Categories/Categories/BMCCategoryCell.xib
  iphone/Maps/Images.xcassets/ic_eye_off.imageset/Contents.json
  iphone/Maps/Images.xcassets/ic_eye_off.imageset/ic_eye_off.svg
  iphone/Maps/Images.xcassets/ic_eye_on.imageset/Contents.json
  iphone/Maps/Images.xcassets/ic_eye_on.imageset/ic_eye_on.svg
Labels: iOS, UI

#7569 [android-auto] FreeDrive Screen
  android/app/src/main/java/app/organicmaps/car/screens/FreeDriveScreen.java
  android/app/src/main/java/app/organicmaps/car/screens/MapScreen.java
  android/app/src/main/res/drawable/ic_steering_wheel.xml
Labels: AndroidAuto

#7607 [ios] Fix bug when the user's 'saved bookmark' tab icon has wrong selected color and icon
  iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.m
Labels: iOS, UI

#7640 [android] Fixed crash when opening PP displaying 24h opening hours with 12h system time format
  android/app/src/main/java/app/organicmaps/editor/data/HoursMinutes.java
Labels: Android, CrashReports

#7669 [android-auto] Auto-start navigation
  android/app/src/main/java/app/organicmaps/car/screens/PlaceScreen.java
Labels: AndroidAuto

#7600 [android-auto] Fix bookmarks screen
  android/app/src/main/java/app/organicmaps/bookmarks/data/Icon.java
  android/app/src/main/java/app/organicmaps/car/screens/BookmarksScreen.java
  android/app/src/main/java/app/organicmaps/car/screens/MapScreen.java
  android/app/src/main/java/app/organicmaps/car/screens/bookmarks/BookmarkCategoriesScreen.java
  android/app/src/main/java/app/organicmaps/car/screens/bookmarks/BookmarksLoader.java
  android/app/src/main/java/app/organicmaps/car/screens/bookmarks/BookmarksScreen.java
Labels: AndroidAuto

#7688 [ios] Fix estimates when the following type is changing
  iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
Labels: iOS

#7721 [android] Change color for disabled texts
  android/app/src/main/res/color/text_color_primary.xml
  android/app/src/main/res/color/text_color_primary_dark.xml
  android/app/src/main/res/color/text_color_secondary.xml
  android/app/src/main/res/color/text_color_secondary_dark.xml
  android/app/src/main/res/values/themes-base.xml
Labels: Android, UX, UI

#7733 [strings] Update of Spanish style translations
  data/strings/types_strings.txt
Labels: Translations
