Repository organicmaps/organicmaps, pull requests merged in 2024-06, with the labels that each got.

#7299 [core] update to c++20
  .clang-format
  CMakeLists.txt
  cmake/OmimHelpers.cmake
  docs/CPP_STYLE.md
Labels: Coverage

#8392 [ios] Fix the issue importing a file from the Files app during the cold start
  iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
Labels: iOS, UI

#8382 [ios] Open social media links in installed applications from the Place Page
  iphone/Maps/Categories/UIKitCategories.h
  iphone/Maps/Categories/UIKitCategories.m
  iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift
  iphone/Maps/UI/Help/AboutController/AboutController.swift
  iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
Labels: iOS, UI

#8452 [ios] Reload the PP content instead of Recreate the entire screen
  iphone/Maps/Classes/MapViewController.mm
  iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
  iphone/Maps/UI/PlacePage/PlacePageBuilder.swift
  iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
  iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
  iphone/Maps/UI/PlacePage/PlacePageViewController.swift
Labels: iOS, UX, UI
