Repository organicmaps/organicmaps, pull requests merged in 2024-08, with the labels that each got.

#8820 [ios] iCloud sync - update the file's content using the `safe replace`
  iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
Labels: iOS

#8819 [ios] Add more logs to the iCloud sync process
  iphone/Maps/Core/iCloud/CloudStorageManager.swift
  iphone/Maps/Core/iCloud/DefaultLocalDirectoryMonitor.swift
  iphone/Maps/Core/iCloud/MetadataItem.swift
  iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
  iphone/Maps/Core/iCloud/SynchronizationStateManager.swift
  iphone/Maps/Core/iCloud/iCloudDocumentsDirectoryMonitor.swift
Labels: iOS

#8859 [android-auto] Add 3d buildings option in settings
  android/app/src/main/java/app/organicmaps/car/screens/settings/SettingsScreen.java
Labels: AndroidAuto

#8853 [ios] Write the Error and Critical messages to the log file synchronously in the current thread
  iphone/CoreApi/CoreApi/Logger/Logger.mm
Labels: iOS

#8851 [ios] Add more logs to the `Location manager`
  iphone/Maps/Core/Location/MWMLocationManager.mm
Labels: iOS

#8836 [android-auto] Fix turn directions
  android/app/src/main/cpp/app/organicmaps/Framework.cpp
  android/app/src/main/java/app/organicmaps/car/util/RoutingUtils.java
  android/app/src/main/java/app/organicmaps/routing/RoutingInfo.java
  iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
  iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.mm
  qt/draw_widget.cpp
  routing/following_info.hpp
  routing/route.cpp
  routing/route.hpp
  routing/routing_session.cpp
Labels: AndroidAuto

#8929 Properly recreate the recent track storage file if it is corrupted/empty
  map/gps_track_storage.cpp
Labels: Track Recording

#8997 Fixed wrongly selected bookmarks instead of search results
  map/framework.cpp
Labels: Regression

#8998 [ios] Configure audio session once with AVAudioSessionModeVoicePrompt
  iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm
Labels: iOS, TTS

#9083 [ios] Fix the icloud trashing bug
  iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
Labels: iOS

#9093 [ios] fix Recent Path cell title localized string
  iphone/Maps/UI/Settings/MWMSettingsViewController.mm
Labels: iOS

#8860 [android-auto] Remove android:foregroundServiceType="location" from CarAppService
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/donottranslate.xml
Labels: Android Auto
