Repository organicmaps/organicmaps, pull requests merged in 2025-05, with the labels that each got.

#10547 [ios] fix Placeholder view animation
  iphone/Maps/UI/Search/SearchOnMap/PlaceholderView.swift
Labels: iOS, UI

#10574 [ios] Fix search count calculation for `?edits` debug command
  iphone/Maps/Core/Search/MWMSearch.mm
Labels: iOS, UI

#10569 [ios] Fix the bookmark's wiki section visibility on the Place Page
  iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
Labels: iOS, UI

#10590 [ios] Fully expand the track PP when opened
  iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageTrackLayout.swift
Labels: iOS, UI

#10597 [ios] Increase search screen top inset from the safe area
  iphone/Maps/UI/Search/SearchOnMap/Presentation/ModalPresentationStep.swift
Labels: iOS, UI

#10591 [ios] Make modal screen appearanсe animation smoother
  iphone/Maps/UI/Search/SearchOnMap/Presentation/ModalPresentationAnimator.swift
Labels: iOS, UI

#10592 [ios] update side buttons animation
  iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
  iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
  iphone/Maps/Classes/MapViewController.mm
Labels: iOS, UI

#10528 [routing] Add possibility to save routes as tracks
  android/app/src/main/cpp/app/organicmaps/Framework.cpp
  android/app/src/main/java/app/organicmaps/Framework.java
  android/app/src/main/java/app/organicmaps/routing/RoutingBottomMenuController.java
  android/app/src/main/java/app/organicmaps/routing/RoutingPlanController.java
  android/app/src/main/res/layout-land/altitude_chart_panel.xml
  android/app/src/main/res/layout-w1020dp-land/altitude_chart_panel.xml
  android/app/src/main/res/layout/altitude_chart_panel.xml
  android/app/src/main/res/values/strings.xml
  map/bookmark_manager.cpp
  map/bookmark_manager.hpp
  map/framework.cpp
  map/framework.hpp
  map/map_tests/bookmarks_test.cpp
  map/routing_manager.cpp
  map/routing_manager.hpp
  qt/routing_turns_visualizer.cpp
Labels: Android

#10546 [ci] Display Android Lint report
  .github/workflows/android-check.yaml
Labels: DevOps

#10624 [ios] Fix PlacePage layout for the iPad in SplitView mode
  iphone/Maps/Categories/UIViewController+alternative.swift
  iphone/Maps/Common/Common.swift
  iphone/Maps/Core/Theme/GlobalStyleSheet.swift
  iphone/Maps/Core/Theme/PlacePageStyleSheet.swift
  iphone/Maps/Tests/UI/SearchOnMapTests/SearchOnMapTests.swift
  iphone/Maps/UI/Search/SearchOnMap/SearchOnMapInteractor.swift
Labels: iOS, UI
